from pyspark.sql import SparkSession, functions, types
import sys
from pprint import pprint
import pandas as pd
import numpy as np
import glob

spark = SparkSession.builder.appName('test').getOrCreate()
spark.sparkContext.setLogLevel('WARN')

assert sys.version_info >= (3, 5) # make sure we have Python 3.5+
assert spark.version >= '2.3' # make sure we have Spark 2.3+


# weather_schema = types.StructType([
#     types.StructField('STATION', types.StringType()),
#     types.StructField('DATE', types.StringType()),
#     types.StructField('LATITUDE', types.DoubleType()),
#     types.StructField('LONGITUDE', types.DoubleType()),
#     types.StructField('ELEVATION', types.DoubleType()),
#     types.StructField('NAME', types.StringType()),
#     types.StructField('CDSD', types.StringType()),
#     types.StructField('CDSD_ATTRIBUTES', types.StringType()),
#     types.StructField('CLDD', types.DoubleType()),
#     types.StructField('CLDD_ATTRIBUTES', types.StringType()),
#     types.StructField('DP01', types.DoubleType()),
#     types.StructField('DP01_ATTRIBUTES', types.StringType()),
#     types.StructField('DP10', types.LongType()),
#     types.StructField('DP10_ATTRIBUTES', types.StringType()),
#     types.StructField('DP1X', types.LongType()),
#     types.StructField('DP1X_ATTRIBUTES', types.StringType()),
#     types.StructField('DSND', types.LongType()),
#     types.StructField('DSND_ATTRIBUTES', types.StringType()),
#     types.StructField('DSNW', types.LongType()),
#     types.StructField('DSNW_ATTRIBUTES', types.StringType()),
#     types.StructField('DT00', types.LongType()),
#     types.StructField('DT00_ATTRIBUTES ', types.StringType()),
#     types.StructField('DT32', types.LongType()),
#     types.StructField('DT32_ATTRIBUTES', types.StringType()),
#     types.StructField('DX32', types.LongType()),
#     types.StructField('DX32_ATTRIBUTES', types.StringType()),
#     types.StructField('DX70', types.LongType()),
#     types.StructField('DX70_ATTRIBUTES', types.StringType()),
#     types.StructField('DX90', types.LongType()),
#     types.StructField('DX90_ATTRIBUTES', types.StringType()),
#     types.StructField('DYFG', types.LongType()),
#     types.StructField('DYHF', types.LongType()),
#     types.StructField('DYTS', types.LongType()),
#     types.StructField('EMNT', types.DoubleType()),
#     types.StructField('EMNT_ATTRIBUTES', types.StringType()),
#     types.StructField('EMSD', types.LongType()),
#     types.StructField('EMSD_ATTRIBUTES', types.StringType()),
#     types.StructField('EMSN', types.LongType()),
#     types.StructField('EMSN_ATTRIBUTES', types.StringType()),
#     types.StructField('EMXP', types.LongType()),
#     types.StructField('EMXP_ATTRIBUTES', types.StringType()),
#     types.StructField('EMXT', types.DoubleType()),
#     types.StructField('EMXT_ATTRIBUTES', types.StringType()),
#     types.StructField('EVAP', types.DoubleType()),
#     types.StructField('EVAP_ATTRIBUTES', types.StringType()),
#     types.StructField('HDSD', types.DoubleType()),
#     types.StructField('HDSD_ATTRIBUTES', types.StringType()),
#     types.StructField('HNN01', types.DoubleType()),
#     types.StructField('HN01_ATTRIBUTES', types.StringType()),
#     types.StructField('HNN02', types.DoubleType()),
#     types.StructField('HN02_ATTRIBUTES', types.StringType()),
#     types.StructField('HNN03', types.DoubleType()),
#     types.StructField('HN03_ATTRIBUTES', types.StringType()),
#     types.StructField('HNN04', types.DoubleType()),
#     types.StructField('HN04_ATTRIBUTES', types.StringType()),
#     types.StructField('HTDD', types.DoubleType()),
#     types.StructField('HTDD_ATTRIBUTES', types.StringType()),
#     types.StructField('HX01', types.DoubleType()),
#     types.StructField('HX01_ATTRIBUTES', types.StringType()),
#     types.StructField('HX02', types.DoubleType()),
#     types.StructField('HX02_ATTRIBUTES', types.StringType()),
#     types.StructField('HX03', types.DoubleType()),
#     types.StructField('HX03_ATTRIBUTES', types.StringType()),
#     types.StructField('HX04', types.DoubleType()),
#     types.StructField('HX04_ATTRIBUTES', types.StringType()),
#     types.StructField('HX05', types.DoubleType()),
#     types.StructField('HX05_ATTRIBUTES', types.StringType()),
#     types.StructField('LNN01', types.DoubleType()),
#     types.StructField('LNN01_ATTRIBUTES', types.StringType()),
#     types.StructField('LNN02', types.DoubleType()),
#     types.StructField('LNN02_ATTRIBUTES', types.StringType()),
#     types.StructField('LNN03', types.DoubleType()),
#     types.StructField('LNN03_ATTRIBUTES', types.StringType()),
#     types.StructField('LNN04', types.DoubleType()),
#     types.StructField('LNN04_ATTRIBUTES', types.StringType()),
#     types.StructField('LX01', types.DoubleType()),
#     types.StructField('LX01_ATTRIBUTES', types.StringType()),
#     types.StructField('LX02', types.DoubleType()),
#     types.StructField('LX02_ATTRIBUTES', types.StringType()),
#     types.StructField('LX03', types.DoubleType()),
#     types.StructField('LX03_ATTRIBUTES', types.StringType()),
#     types.StructField('LX04', types.DoubleType()),
#     types.StructField('LX04_ATTRIBUTES', types.StringType()),
#     types.StructField('LX05', types.DoubleType()),
#     types.StructField('LX05_ATTRIBUTES', types.StringType()),
#     types.StructField('MN01', types.DoubleType()),
#     types.StructField('MN01_ATTRIBUTES', types.StringType()),
#     types.StructField('MN02', types.DoubleType()),
#     types.StructField('MN02_ATTRIBUTES', types.StringType()),
#     types.StructField('MN03', types.DoubleType()),
#     types.StructField('MN03_ATTRIBUTES', types.StringType()),
#     types.StructField('MN04', types.DoubleType()),
#     types.StructField('MN04_ATTRIBUTES', types.StringType()),
#     types.StructField('MX01', types.DoubleType()),
#     types.StructField('MX01_ATTRIBUTES', types.StringType()),
#     types.StructField('MX02', types.DoubleType()),
#     types.StructField('MX02_ATTRIBUTES', types.StringType()),
#     types.StructField('MX03', types.DoubleType()),
#     types.StructField('MX03_ATTRIBUTES', types.StringType()),
#     types.StructField('MX04', types.DoubleType()),
#     types.StructField('MX04_ATTRIBUTES', types.StringType()),
#     types.StructField('MX05', types.DoubleType()),
#     types.StructField('MX05_ATTRIBUTES', types.StringType()),
#     types.StructField('MXPN', types.DoubleType()),
#     types.StructField('MXPN_ATTRIBUTES', types.StringType()),
#     types.StructField('PRCP', types.DoubleType()),
#     types.StructField('PRCP_ATTRIBUTES', types.StringType()),
#     types.StructField('SNOW', types.DoubleType()),
#     types.StructField('SNOW_ATTRIBUTES', types.StringType()),
#     types.StructField('TAVG', types.DoubleType()),
#     types.StructField('TAVG_ATTRIBUTES', types.StringType()),
#     types.StructField('TMAX', types.DoubleType()),
#     types.StructField('TMAX_ATTRIBUTES', types.StringType()),
#     types.StructField('TMIN', types.DoubleType()),
#     types.StructField('TMIN_ATTRIBUTES', types.StringType()),
#     types.StructField('WDMV', types.DoubleType()),
#     types.StructField('WDMV_ATTRIBUTES', types.StringType()),
    
# ])


def main(in_directory):
    att = spark.read.option("header", "true").csv(in_directory)
    att = att.cache()
    df = att.select(
        att['STATION'],
        att['NAME'].alias("STATION_NAME"),
        att['LATITUDE'],
        att['LONGITUDE'],
        att['ELEVATION'],
        att['DATE'],
        att['CLDD'],
        att['DP01'],
        att['DSND'],
        att['DSNW'],
        att['DT00'],
        # att['DT32'],
        # att['DX70'],
        # att['DX90'],
        # att['DYFG'],
        # att['DYTS'],
        # att['EMNT'],
        # att['EMSD'],
        # att['EMSN'],
        # att['EMXP'],
        # att['EMXT'],
        # att['EVAP'],
        # # att['HTDD'],
        # # att['HN01'],
        # # att['HN02'],
        # # att['HN03'],
        # # att['HN04'],
        # # att['HX01'],
        # # att['HX02'],
        # # att['HX03'],
        # # att['HX04'],
        # # att['LN01'],
        # # att['LN02'],
        # # att['LN03'],
        # # att['LX01'],
        # # att['LX02'],
        # # att['LX03'],
        # # att['LX04'],
        # att['MN01'],
        # att['MN02'],
        # att['MN03'],
        # att['MN04'],
        # att['MX01'],
        # att['MX02'],
        # att['MX03'],
        # att['MX04'],
        # att['PRCP'],
        # att['SNOW'],
        # att['TAVG'],
        # att['TMAX'],
        # att['TMIN'],
    )
    # df.filter(df.DP01.isNull()).show()
    # df = df.select('DP01').filter(df.DP01.isNotNull())
    df =df.drop()
    print(df.schema)
    df.show()

if __name__ == '__main__':
    in_directory = sys.argv[1]
    main(in_directory)
